plugins {
    id 'application'
}

dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'org.jsoup:jsoup:1.17.2'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'org.json:json:20231013'

    // SMB/Samba support
    implementation 'com.hierynomus:smbj:0.12.2'
}

application {
    mainClass = 'com.github.catvod.demo.TestRunner'
}

// tasks.withType(JavaCompile) {
//     options.encoding = 'UTF-8'
// }

// run {
//     standardInput = System.in
// }

// compileJava {
//     options.encoding = 'UTF-8'
// }
// compileTestJava {
//     options.encoding = 'UTF-8'
// }
